org: scouredimage
app: northside
service: bot

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
    keepOutputDirectory: trues
    excludeFiles: src/**/*.test.[t|j]s

provider:
  name: aws
  runtime: nodejs12.x
  environment:
    SLACK_SIGNING_SECRET: ${param:SLACK_SIGNING_SECRET}
    SLACK_ACCESS_TOKEN: ${param:SLACK_ACCESS_TOKEN}
    DEBUG: '@slack/events-api:*'
    SPOTIFY_CLIENT_ID: ${param:SPOTIFY_CLIENT_ID}
    SPOTIFY_CLIENT_SECRET: ${param:SPOTIFY_CLIENT_SECRET}
    SPOTIFY_REQUEST_SCOPES: playlist-modify-public
    SPOTIFY_AUTH_REDIRECT_URI: https://ila7pk2i01.execute-api.us-east-1.amazonaws.com/live/spotify/authorized
    SPOTIFY_TRACK_PLAYLIST_ID: 32NmYcDmYu6cGSaPESsBtk
    SPOTIFY_ALBUM_PLAYLIST_ID: 6FVg5NqAKnLg9xTsfSyr8c
    SPOTIFY_PLAYLIST_PLAYLIST_ID: 0ejE8EJCGir9ntGEWCA7Ne

functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'