org: scouredimage
app: northside
service: bot

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-domain-manager

custom:
  stage: ${opt:stage, self:provider.stage}
  target: ${self:custom.${self:custom.stage}}
  tablename: northside-${self:custom.stage}
  dev:
    domain: dev.northside.link
    playlist:
      tracks: 32NmYcDmYu6cGSaPESsBtk
      albums: 32NmYcDmYu6cGSaPESsBtk
      playlists: 32NmYcDmYu6cGSaPESsBtk
  live:
    domain: northside.link
    playlist:
      tracks: 0EDmWH7RPv1aK4rN2I0tcV
      albums: 6FVg5NqAKnLg9xTsfSyr8c
      playlists: 0ejE8EJCGir9ntGEWCA7Ne
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
    keepOutputDirectory: trues
    excludeFiles: src/**/*.test.[t|j]s
  customDomain:
    domainName: ${self:custom.target.domain}
    basePath: ''
    stage: ${self:custom.stage}
    createRoute53Record: true

provider:
  name: aws
  runtime: nodejs12.x
  environment:
    DB_TABLE_NAME: ${self:custom.tablename}
    SLACK_CLIENT_ID: ${param:SLACK_CLIENT_ID}
    SLACK_CLIENT_SECRET: ${param:SLACK_CLIENT_SECRET}
    SLACK_SIGNING_SECRET: ${param:SLACK_SIGNING_SECRET}
    SLACK_AUTH_SCOPES: 'links:read,team:read,chat:write'
    SLACK_AUTH_REDIRECT_URI: https://${self:custom.target.domain}/slack/authorized
    # DEBUG: '@slack/events-api:*'
    SPOTIFY_CLIENT_ID: ${param:SPOTIFY_CLIENT_ID}
    SPOTIFY_CLIENT_SECRET: ${param:SPOTIFY_CLIENT_SECRET}
    SPOTIFY_REQUEST_SCOPES: playlist-modify-public
    SPOTIFY_AUTH_REDIRECT_URI: https://${self:custom.target.domain}/spotify/authorized
    SPOTIFY_TRACK_PLAYLIST_ID: ${self:custom.target.playlist.tracks}
    SPOTIFY_ALBUM_PLAYLIST_ID: ${self:custom.target.playlist.albums}
    SPOTIFY_PLAYLIST_PLAYLIST_ID: ${self:custom.target.playlist.playlists}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:BatchWriteItem
      Resource:
        - 'arn:aws:dynamodb:*:*:table/${self:custom.tablename}'
    - Effect: Allow
      Action:
        - dynamodb:Query
      Resource:
        - 'arn:aws:dynamodb:*:*:table/${self:custom.tablename}/index/*'

functions:
  slackLogin:
    handler: handler.slackLogin
    events:
      - http:
          method: GET
          path: /slack/login
  slackAuthorized:
    handler: handler.slackAuthorized
    events:
      - http:
          method: GET
          path: /slack/authorized
  slackEvent:
    handler: handler.slackEvents
    events:
      - http:
          method: ANY
          path: /slack/events
      - http:
          method: ANY
          path: '/slack/events/{proxy+}'
  spotifyLogin:
    handler: handler.spotifyLogin
    events:
      - http:
          method: GET
          path: /spotify/login
  spotifyAuthorized:
    handler: handler.spotifyAuthorized
    events:
      - http:
          method: GET
          path: /spotify/authorized

resources:
  Resources:
    DeploymentsTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        TableName: ${self:custom.tablename}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: space
            AttributeType: S
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: space
            KeyType: HASH
          - AttributeName: id
            KeyType: RANGE